services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - VITE_API_URL=http://localhost:3000/api/
      - VITE_SOCKET_URL=http://localhost:3000
